<?php

/*
 * Metadata for Payment Plan Settings
 */
return [
  'membershipextras_paymentplan_use_membership_latest_price' => [
    'group_name' => 'MembershipExtras: Payment Plan',
    'group' => 'membershipextras_paymentplan',
    'name' => 'membershipextras_paymentplan_use_membership_latest_price',
    'title' => 'Use latest price when auto renew membership?',
    'type' => 'Integer',
    'html_type' => 'checkbox',
    'quick_form_type' => 'Element',
    'default' => FALSE,
    'is_required' => FALSE,
  ],
  'membershipextras_paymentplan_default_processor' => [
    'name' => 'membershipextras_paymentplan_default_processor',
    'group_name' => 'MembershipExtras: Payment Plan',
    'group' => 'membershipextras_paymentplan',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'add' => '4.7',
    'pseudoconstant' => [
      'name' =>  'paymentProcessor',
    ],
    'title' => 'Offline payment processor for back office',
    'html_type' => 'select',
    'is_required' => TRUE,
    'description' => 'Select the payment processor that should be used when creating payment plans via CiviCRM admin interface such as new/ renew membership.',
    'help_text' => 'Select the payment processor that should be used when creating payment plans via CiviCRM admin interface such as new/ renew membership.',
  ],
  'membershipextras_paymentplan_days_to_renew_in_advance' => [
    'name' => 'membershipextras_paymentplan_days_to_renew_in_advance',
    'group_name' => 'MembershipExtras: Payment Plan',
    'group' => 'membershipextras_paymentplan',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'add' => '4.7',
    'title' => 'Days to renew in advance',
    'html_type' => 'text',
    'is_required' => FALSE,
    'description' => 'Number of days in advance of membership end date should an offline auto-renew membership get renewed.',
    'help_text' => 'Number of days in advance of membership end date should an offline auto-renew membership get renewed.',
  ],
  'membershipextras_customgroups_to_exclude_for_autorenew' => [
    'name' => 'membershipextras_customgroups_to_exclude_for_autorenew',
    'group_name' => 'MembershipExtras: Payment Plan',
    'group' => 'membershipextras_paymentplan',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'add' => '4.7',
    'title' => 'Custom groups to be excluded when auto-renew"',
    'html_type' => 'select',
    'is_required' => FALSE,
    'extra_attributes' => [
      'class' => 'crm-select2',
      'multiple' => 'multiple',
      'placeholder' => ts('- select -'),
    ],
  ],
  'membershipextras_membership_period_rules_automatically_update_membership_period_with_overdue_payment' => [
    'name' => 'membershipextras_membership_period_rules_automatically_update_membership_period_with_overdue_payment',
    'group_name' => 'MembershipExtras: Membership Period Rules',
    'group' => 'membershipextras_membership_period_rules',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => FALSE,
    'add' => '4.7',
    'title' => "Automatically update a membership period when it's payment is overdue",
    'html_type' => 'checkbox',
    'is_required' => FALSE,
    'description' => "Automatically update a membership period when it's payment is overdue",
    'help_text' => '',
    'has_children' => TRUE,
  ],
  'membershipextras_membership_period_rules_days_to_act_on_membership_period_with_overdue_payment' => [
    'name' => 'membershipextras_membership_period_rules_days_to_act_on_membership_period_with_overdue_payment',
    'group_name' => 'MembershipExtras: Membership Period Rules',
    'group' => 'membershipextras_membership_period_rules_automatically_update_membership_period_with_overdue_payment',
    'is_child_of' => 'membershipextras_membership_period_rules_automatically_update_membership_period_with_overdue_payment',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'add' => '4.7',
    'title' => 'How many days after overdue',
    'html_type' => 'text',
    'is_required' => FALSE,
    'description' => 'Days after a payment is overdue that a membership period should become inactive',
    'help_text' => 'Days after a payment is overdue that a membership period should become inactive',
    'extra_attributes' => [
      'maxlength' => 3,
    ],
  ],
  'membershipextras_membership_period_rules_action_on_period_with_overdue_payment' => [
    'name' => 'membershipextras_membership_period_rules_action_on_period_with_overdue_payment',
    'group_name' => 'MembershipExtras: Membership Period Rules',
    'group' => 'membershipextras_membership_period_rules_automatically_update_membership_period_with_overdue_payment',
    'is_child_of' => 'membershipextras_membership_period_rules_automatically_update_membership_period_with_overdue_payment',
    'type' => 'Integer',
    'add' => '4.7',
    'title' => "Automatic action to take when a membership period payment is overdue",
    'html_type' => 'radio',
    'is_required' => FALSE,
    'description' => '',
    'help_text' => '',
    'options' => ['1' => ts('Deactivate the period'), '2' => ts('Update the period end date')],
    'separator' => '&nbsp;<a class="helpicon" title=" Help" aria-label=" Help" href="#" onclick="CRM.help(&quot;&quot;, {
        &quot;id&quot;:&quot;membershipextras_membership_period_rules_action_on_period_with_overdue_payment_1&quot;,&quot;file&quot;:&quot;CRM\/MembershipExtras\/Form\/PeriodRules&quot;
      }); return false;">&nbsp;</a><br/>',
    'has_children' => TRUE,
    'show_children_only_when_true' => TRUE,
  ],
  'membershipextras_membership_period_rules_update_the_period_end_date_to' => [
    'name' => 'membershipextras_membership_period_rules_update_the_period_end_date_to',
    'group_name' => 'MembershipExtras: Membership Period Rules',
    'group' => 'membershipextras_membership_period_rules_action_on_period_with_overdue_payment',
    'is_child_of' => 'membershipextras_membership_period_rules_action_on_period_with_overdue_payment',
    'type' => 'Integer',
    'add' => '4.7',
    'title' => 'Update the period end date to:',
    'html_type' => 'radio',
    'is_required' => FALSE,
    'help_text' => '',
    'options' => ['1' => ts('Overdue payment receive date'), '2' => ts('Today')]
  ],
  'membershipextras_membership_period_rules_update_period_end_date_offset' => [
    'name' => 'membershipextras_membership_period_rules_update_period_end_date_offset',
    'group_name' => 'MembershipExtras: Membership Period Rules',
    'group' => 'membershipextras_membership_period_rules_action_on_period_with_overdue_payment',
    'is_child_of' => 'membershipextras_membership_period_rules_action_on_period_with_overdue_payment',
    'type' => 'Integer',
    'add' => '4.7',
    'title' => 'Offset',
    'html_type' => 'text',
    'is_required' => FALSE,
    'help_text' => ts('The period end date will be set to the option selected above plus a number of days specified in the offset. This can be a negative number.'),
    'extra_attributes' => [
      'maxlength' => 2,
    ],
  ],
  'membershipextras_paymentmethods_that_always_activate_memberships' => [
    'name' => 'membershipextras_paymentmethods_that_always_activate_memberships',
    'group_name' => 'MembershipExtras: Payment Plan',
    'group' => 'membershipextras_paymentplan',
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'add' => '4.7',
    'title' => 'Payment methods that always activate memberships',
    'html_type' => 'select',
    'is_required' => FALSE,
    'extra_attributes' => [
      'class' => 'crm-select2',
      'multiple' => 'multiple',
      'placeholder' => ts('- select -'),
    ],
  ],
];
